# Default configuration for Spire OIDC Provider chart
# SPDX-License-Identifier: APACHE-2.0

## @skip global
global: {}

## @section Chart parameters
## @param agentSocketName The name of the spire-agent unix socket
##
agentSocketName: spire-agent.sock

## @param replicaCount Replica count 
replicaCount: 1

## @param namespaceOverride Namespace override 
namespaceOverride: ""

## @param annotations Annotations for the deployment
annotations: {}

image:
  ## @param image.registry The OCI registry to pull the image from
  ## @param image.repository The repository within the registry
  ## @param image.pullPolicy The image pull policy
  ## @param image.version This value is deprecated in favor of tag. (Will be removed in a future release)
  ## @param image.tag Overrides the image tag whose default is the chart appVersion
  ##
  registry: ghcr.io
  repository: spiffe/oidc-discovery-provider
  pullPolicy: IfNotPresent
  version: ""
  tag: ""

## @param resources Resource requests and limits
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # requests:
  #   cpu: 50m
  #   memory: 32Mi
  # limits:
  #   cpu: 100m
  #   memory: 64Mi

## @param service.type Service type
## @param service.port Service port
## @param service.annotations Annotations for service resource
##
service:
  type: ClusterIP
  port: 80
  annotations: {}
  # external-dns.alpha.kubernetes.io/hostname: oidc-discovery.example.org

## @param configMap.annotations Annotations to add to the SPIFFE OIDC Discovery Provider ConfigMap
configMap:
  annotations: {}

## @param podSecurityContext Pod security context for OIDC discovery provider pods
podSecurityContext: {}
  # fsGroup: 2000

## @param securityContext Security context for OIDC discovery provider deployment
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
## @param readinessProbe.periodSeconds Period seconds for readinessProbe
##
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5

## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
## @param livenessProbe.periodSeconds Period seconds for livenessProbe
##
livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5

## @param podAnnotations Pod annotations for Spire OIDC discovery provider
podAnnotations: {}

insecureScheme:
  ## @param insecureScheme.enabled Flag to enable insecure schema
  enabled: false

  nginx:
    ## @param insecureScheme.nginx.image.registry The OCI registry to pull the image from
    ## @param insecureScheme.nginx.image.repository The repository within the registry
    ## @param insecureScheme.nginx.image.pullPolicy The image pull policy
    ## @param insecureScheme.nginx.image.version This value is deprecated in favor of tag. (Will be removed in a future release)
    ## @param insecureScheme.nginx.image.tag Overrides the image tag whose default is the chart appVersion
    ## Example:
    ## chainguard image does not support the templates feature
    ## https://github.com/chainguard-images/nginx/issues/43
    ## registry: cgr.dev
    ## repository: chainguard/nginx
    ## pullPolicy: IfNotPresent
    ## tag: "1.23.2"
    ##
    image:
      registry: docker.io
      repository: nginxinc/nginx-unprivileged
      pullPolicy: IfNotPresent
      version: ""
      tag: 1.24.0-alpine
    ## @param insecureScheme.nginx.resources Resource requests and limits
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # requests:
      #   cpu: 50m
      #   memory: 32Mi
      # limits:
      #   cpu: 100m
      #   memory: 64Mi

## @param jwtIssuer Path to JWT issuer
jwtIssuer: https://oidc-discovery.example.org

config:
  ## @param config.logLevel The log level, valid values are "debug", "info", "warn", and "error"
  logLevel: info
  ## @param config.additionalDomains [array] Add additional domains that can be used for oidc discovery
  additionalDomains:
    - localhost

  ## @param config.acme.tosAccepted Flag for Terms of Service acceptance
  ## @param config.acme.cacheDir Path for cache directory
  ## @param config.acme.directoryUrl URL for acme directory
  ## @param config.acme.emailAddress Email address for registration
  ##
  acme:
    tosAccepted: false
    cacheDir: /run/spire
    directoryUrl: https://acme-v02.api.letsencrypt.org/directory
    emailAddress: letsencrypt@example.org

## @param imagePullSecrets [array] Image pull secret names
imagePullSecrets: []

## @param nameOverride Name override
nameOverride: ""

## @param fullnameOverride Full name override
fullnameOverride: ""

serviceAccount:
  ## @param serviceAccount.create Specifies whether a service account should be created
  create: true
  ## @param serviceAccount.annotations Annotations to add to the service account
  annotations: {}
  ## @param serviceAccount.name The name of the service account to use. 
  ## If not set and create is true, a name is generated using the fullname template
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

## @param nodeSelector Node selector
nodeSelector: {}

## @param tolerations List of tolerations
tolerations: []

## @param affinity Node affinity
affinity: {}

## @param trustDomai Set the trust domain to be used for the SPIFFE identifiers
trustDomain: example.org

## @param clusterDomain The name of the Kubernetes cluster (`kubeadm init --service-dns-domain`)
clusterDomain: cluster.local

telemetry:
  prometheus:
    enabled: false
    port: 9988
    podMonitor:
      enabled: false
      ## @param Override where to install the podMonitor, if not set will use the same namespace as the spiffe-oidc-discovery-provider
      namespace: ""
      labels: {}

    nginxExporter:
      image:
        ## @param The OCI registry to pull the image from
        registry: docker.io
        ## @param The repository within the registry
        repository: nginx/nginx-prometheus-exporter
        ## @param The image pull policy
        pullPolicy: IfNotPresent
        ## @param This value is deprecated in favor of tag. (Will be removed in a future release)
        version: ""
        ## @param Overrides the image tag
        tag: "0.11.0"

      resources: {}
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        # requests:
        #   cpu: 50m
        #   memory: 32Mi
        # limits:
        #   cpu: 100m
        #   memory: 64Mi

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: oidc-discovery.example.org
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - oidc-discovery.example.org

# @ignored
tests:
  bash:
    image:
      ## @param The OCI registry to pull the tests image from
      registry: cgr.dev
      ## @param The repository within the registry
      repository: chainguard/bash
      ## @param The tests image pull policy
      pullPolicy: IfNotPresent
      ## @param This value is deprecated in favor of tag. (Will be removed in a future release)
      version: ""
      ## @param Overrides the image tag
      tag: latest@sha256:96ab1600d945b4a99c8610b5c8b31e346da63dc20573a26bb0777dd0190db5d4

tools:
  kubectl:
    image:
      ## @param The OCI registry to pull the image from
      registry: docker.io
      ## @param The repository within the registry
      repository: rancher/kubectl
      ## @param The image pull policy
      pullPolicy: IfNotPresent
      ## @param This value is deprecated in favor of tag. (Will be removed in a future release)
      version: ""
      ## @param Overrides the image tag
      tag: ""
