# Default configuration for Spire chart
# SPDX-License-Identifier: APACHE-2.0

## @section Global parameters
## Note: the paramter values specified here will override the chart level values for these parameters.
##
global:
  k8s:
    ## @param global.k8s.clusterDomain Cluster domain name configured for Spire install
    ##
    clusterDomain: cluster.local
  spire:
    ## @param global.spire.bundleConfigMap A configmap containing the Spire bundle
    ## @param global.spire.clusterName The name of the k8s cluster for Spire install
    ## @param global.spire.image.registry Image registry override
    ## @param global.spire.jwtIssuer The issuer for Spire JWT tokens
    ## @param global.spire.trustDomain The trust domain for Spire install
    ##
    bundleConfigMap: ""
    clusterName: example-cluster
    image:
      registry: ""
    jwtIssuer: oidc-discovery.example.org
    trustDomain: example.org

## @section Spire server parameters
## Parameter values for Spire server
##
spire-server:
  ## @param spire-server.enabled Flag to enable Spire server
  ## @param spire-server.nameOverride Overrides the name of Spire server pods
  ## 
  enabled: true
  nameOverride: server
  ## @param spire-server.controllerManager.enabled Enable controller manager and provision CRD's
  ## 
  controllerManager:
    enabled: true

## @section Spire agent parameters
## Parameter values for Spire agent
##
spire-agent:
  ## @param spire-agent.enabled Flag to enable Spire agent
  ## @param spire-agent.nameOverride Overrides the name of Spire agent pods
  ## 
  enabled: true
  nameOverride: agent

## @section Spire CSI Driver parameters
## Parameter values for spire-csi-driver
##
spiffe-csi-driver:
  ## @param spiffe-csi-driver.enabled Flag to enable spiffe-csi-driver for the cluster
  ## 
  enabled: true

## @section SPIFFE oidc discovery provider parameters
## Parameter values for spiffe-oidc-discovery-provider
##
spiffe-oidc-discovery-provider:
  ## @param spiffe-oidc-discovery-provider.enabled Flag to enable spiffe-oidc-discovery-provider for the cluster
  ## 
  enabled: false

## @section Tornjak frontend parameters
## Parameter values for Tornjak frontend
##
tornjak-frontend:
  ## @param tornjak-frontend.enabled Flag to enable Tronjak frontend
  ##
  enabled: false
