# Default configuration for Spire chart
# SPDX-License-Identifier: APACHE-2.0

## Global parameters
## Note: the paramter values specified here will override the chart level values for these parameters.
##
global:
  k8s:
    # -- cluster domain name configured for Spire install
    clusterDomain: cluster.local
  spire:
    # -- a configmap containing the Spire bundle
    bundleConfigMap: ""
    # -- the name of the k8s cluster for Spire install
    clusterName: example-cluster
    # -- image registry override
    image:
      registry: ""
    # -- the issuer for Spire JWT tokens
    jwtIssuer: oidc-discovery.example.org
    # -- the trust domain for Spire install
    trustDomain: example.org

## Spire server parameters
## Parameter values for Spire server
##
spire-server:
  # -- flag to enable Spire server
  enabled: true
  # -- Overrides the full name of Spire server pods
  fullnameOverride: ""
  # -- Overrides the name of Spire server pods
  nameOverride: server
  # -- Overrides the namespace where Spire server pods are installed
  namespaceOverride: ""
  # -- Cluster name configured for Spire servers
  clusterName: example-cluster
  # -- Cluster domain for Spire servers
  clusterDomain: cluster.local
  # -- Domain name for Spire server trust bundle
  trustDomain: example.org
  # -- Config map name for Spire servers trust bundle
  bundleConfigMap: spire-bundle
  # -- Key type for certificate authority
  caKeyType: rsa-2048
  # -- CA TTL for certificate authority
  caTTL: 24h
  # -- Default TTL for JWT tokens issued by Spire
  defaultJwtSvidTTL: 1h
  # -- Default TTL for X509 tokens issued by Spire
  defaultX509SvidTTL: 4h
  # -- Issuer for JWT tokens
  jwtIssuer: oidc-discovery.example.org
  # -- Log level for Spire servers
  logLevel: info
  # -- Replica count for Spire servers
  replicaCount: 1
  global:
    # -- cluster domain name configured for Spire server
    k8s:
      clusterDomain: cluster.local
    spire:
      # -- bundle config map for Spire server
      bundleConfigMap: ""
      # -- the name of the k8s cluster for Spire server
      clusterName: example-cluster
      image:
        # -- image registry for Spire server
        registry: ""
      # -- JWT Issuer configured for Spire server
      jwtIssuer: oidc-discovery.example.org
      # -- trust domain name configured for Spire server
      trustDomain: example.org
    # -- Configmap annotations
    configMap:
      annotations: {}
    # -- Image details for the installation
    image:
      pullPolicy: IfNotPresent
      registry: ghcr.io
      repository: spiffe/spire-controller-manager
      tag: 0.2.3
      version: ""
    # -- Resource limits and quotas for the installation
    resources: {}
    # -- Security context for the installation
    securityContext: {}
    # -- Service detials
    service:
      annotations: {}
      port: 443
      type: ClusterIP
  # -- Additional volumes to be mounted into the container
  extraVolumes: []
  # -- Liveness probe for the installation
  livenessProbe:
    failureThreshold: 2
    initialDelaySeconds: 15
    periodSeconds: 60
    timeoutSeconds: 3
  # -- Readiness probe for the installation
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5

## @section Spire agent parameters
## Parameter values for Spire agent
##
spire-agent:
  # -- flag to enable Spire server
  enabled: true
  # -- overrides the full name of Spire server pods
  fullnameOverride: ""
  # -- overrides the name of Spire server pods
  nameOverride: server
  # -- overrides the namespace where Spire server pods are installed
  namespaceOverride: ""
  # -- cluster name configured for Spire servers
  clusterName: example-cluster
  # -- format for Spire agent trust bundle
  trustBundleFormat: pem
  # -- URL for Spire agent trust bundle for federation
  trustBundleURL: ""
  # -- domain name for Spire agent trust bundle
  trustDomain: example.org
  # -- config map name for Spire agent trust bundle
  bundleConfigMap: spire-bundle
  # -- path for Spire agent socket
  socketPath: /run/spire/agent-sockets/spire-agent.sock
  # -- log level set for Spire agents
  logLevel: info
  ## @param spire-agent.global.k8s.clusterDomain Cluster domain name configured for Spire agent
  global:
    k8s:
      clusterDomain: cluster.local
    spire:
      # -- spire bundle config map for Spire agent
      bundleConfigMap: ""
      # -- the name of the k8s cluster for Spire agent
      clusterName: example-cluster
      image:
        # == image registry for Spire agent
        registry: ""
      # -- JWT Issuer configured for Spire agent
      jwtIssuer: oidc-discovery.example.org
      # -- trust domain name configured for Spire agent
      trustDomain: example.org
  # -- Configmap annotations
  configMap:
    annotations: {}
  # -- Addiitonal initcontainers to add to the main container
  initContainers: []
  # -- Addiitonal sidecar containers to add to the main container
  extraContainers: []
  # -- Additional volumes to be mounted into the container
  extraVolumes: []
  # -- Image details for the installation
  image:
    pullPolicy: IfNotPresent
    registry: ghcr.io
    repository: spiffe/spire-agent
    tag: ""
    version: ""
  # -- Image pull secrets for pulling from secure registries
  imagePullSecrets: []
  # -- Liveness probe for the installation
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 60
  # -- Rediness probe for the installation
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 60